baseURL                = "https://yaoyao.games"
locale                 = "zh-cn"
title                  = "耀耀游戏"
defaultContentLanguage = "zh"
hasCJKLanguage         = true

[[module.imports]]
    path = "github.com/CaiJimmy/hugo-theme-stack/v3"

[pagination]
    pagerSize = 6

[permalinks]
    post = "/blog/:slug/"
    projects = "/projects/:slug/"
    games = "/games/:slug/"
    page = "/:slug/"

[services.disqus]
    shortname = ""
